#kubectl create -f k8s-keycloak-deployment.yml

apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - nodePort: 30500
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:14.0.0
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "728Mi"
            cpu: "500m"
        env:
        - name: DB_VENDOR
          value: POSTGRES
        - name: DB_ADDR
          value: jlstechnology.postgres.database.azure.com
        - name: DB_DATABASE
          value: postgres
        - name: DB_SCHEMA
          value: public
        - name: DB_USER
          value: thiagoporb@jlstechnology
        - name: DB_PASSWORD
          value: Porb13ch@
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "porb13"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
